# Server constants
[server]
tick_ms = 30

# Lobby constants
[lobby]
tick_ms = 1000
pool_size = 4
max_players = 15

# Map initialization constants
[map_gen.water]
spreading = "Water"
spreads_on = ["Grass"]
iterations = 15
percent = 45
counts_to_spread = 5
counts_to_survive = 4

[map_gen.woods]
spreading = "Woods"
spreads_on = ["Grass"]
iterations = 10
percent = 35
counts_to_spread = 4
counts_to_survive = 4

[map_gen.mountain]
spreading = "Mountain"
spreads_on = ["Grass", "Woods"]
iterations = 10
percent = 99
counts_to_spread = 7
counts_to_survive = 6

[map_gen.high_mountain]
spreading = "HighMountain"
spreads_on = ["Mountain"]
iterations = 7
percent = 30
counts_to_spread = 4
counts_to_survive = 4
